[tool.ruff]
indent-width = 4
line-length = 100
target-version = "py312"
exclude = ["build", "dist", ".git", "__pycache__"]

[tool.ruff.format]
docstring-code-format = true
indent-style = "space"
line-ending = "auto"
quote-style = "double"
